import java.io.FileNotFoundException;

import spark.Filter;

import static spark.Spark.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws FileNotFoundException {
        enableCORS();

        // Respond to new editor request
        get("/getI3Mapping", new I3Route());

    }

    private static void enableCORS() {
        before((Filter) (request, response) -> {
            response.header("Access-Control-Allow-Origin", "*");
            response.header("Access-Control-Request-Method", "*");
            response.header("Access-Control-Allow-Headers", "*");
        });
    }
}
